import Head from 'next/head';
import { useEffect, useState } from 'react';
import { AuthForm } from '../components/AuthForm';
import { CreatePost } from '../components/CreatePost';
import { Post } from '../components/Post';
import { useMe } from '../utils/hooks';

export default function Home() {
  const [loggedIn, setLoggedIn] = useState(false);

  const { me } = useMe();

  useEffect(() => {
    if (me) {
      // we check if the query useMe() return an empty Obj
      const isEmpty: boolean = Object.keys(me).length == 0;
      isEmpty ? setLoggedIn(false) : setLoggedIn(true);
    }
  }, [me]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!loggedIn ? <AuthForm isOnRoute={false} /> : <CreatePost />}
      <Post />
    </>
  );
}
